name: trapmouse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  go_router: ^15.1.1
  google_maps_flutter: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/dash.png
    - assets/TrapSyncLogo-01.png